### ISSUE TITLE
Size too small

### ISSUE THREAD

**Issue by nwalmethule** [emperorcal/gdax-tradingbot#4]
Hallo,
I trying the code now, but look like there is a problem with the fee. The message I had is:
'size is too small. Minimum size is 0.01'
I will try to fix it and I let you know.

**Comment by calum-mcg** [comment]
Thanks for letting me know. This is most likely an API message from GDAX that is being called due to an order size (buy or sell) being too small.
Could you please provide a bit more info about how this is happening (previous console outputs etc.) and I will look into it.
